// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD_CiI9HVrfmk4kgQiCVtMuXU9n9Ombrw',
    appId: '1:961258065108:web:83a11b03b482bd9d38ff41',
    messagingSenderId: '961258065108',
    projectId: 'order-up-87759',
    authDomain: 'order-up-87759.firebaseapp.com',
    storageBucket: 'order-up-87759.firebasestorage.app',
    measurementId: 'G-HH21PVN4ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATR6rT7WlQV1jsD319Ml7DzlzV0-ZSh_s',
    appId: '1:961258065108:android:23f32d58edc3674438ff41',
    messagingSenderId: '961258065108',
    projectId: 'order-up-87759',
    storageBucket: 'order-up-87759.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN53OEhrRyHCUZajNH5jPS8Z2KSd92JM8',
    appId: '1:961258065108:ios:80e55dde1213d61838ff41',
    messagingSenderId: '961258065108',
    projectId: 'order-up-87759',
    storageBucket: 'order-up-87759.firebasestorage.app',
    iosBundleId: 'com.example.orderUpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN53OEhrRyHCUZajNH5jPS8Z2KSd92JM8',
    appId: '1:961258065108:ios:80e55dde1213d61838ff41',
    messagingSenderId: '961258065108',
    projectId: 'order-up-87759',
    storageBucket: 'order-up-87759.firebasestorage.app',
    iosBundleId: 'com.example.orderUpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD_CiI9HVrfmk4kgQiCVtMuXU9n9Ombrw',
    appId: '1:961258065108:web:881bc0619a55f74238ff41',
    messagingSenderId: '961258065108',
    projectId: 'order-up-87759',
    authDomain: 'order-up-87759.firebaseapp.com',
    storageBucket: 'order-up-87759.firebasestorage.app',
    measurementId: 'G-MGREV2HZKJ',
  );

}